[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".fonts"]
    type = "git-repo"
    url = "https://github.com/powerline/fonts.git"
    refreshPeriod = "168h"
